sudo: false
language: generic
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libusb-1.0-0-dev
    - pkg-config
cache:
  directories:
    - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack build --split-objs
- cp .stack-work/install/*/*/*/bin/trillium .
- >
    tar -c -v -J -f trillium-tester-linux-x86_64-$(grep -Po 'version: *\K[0-9.]+' trillium.cabal).tar.xz --numeric-owner trillium
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "trillium-*.tar.xz"
  skip-cleanup: true
  on:
    repo: UBCOrbit/trillium-tester
    tags: true
