before_build:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe
- set PATH=C:\msys64\usr\bin;%PATH%
- pacman -Sy mingw64/mingw-w64-x86_64-libusb pkg-config --noconfirm

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
    TMP: "c:\\tmp"

install:
   - choco install InnoSetup

build_script:
- stack setup
- stack build --extra-include-dirs=C:\msys64\mingw64\include\libusb-1.0 --extra-lib-dirs=C:\msys64\mingw64\bin
- cd installer
- bash prepare_installer.sh
- ISCC /Q installer.iss
- mv Output/trillium-tester-installer.exe ../trillium-tester-windows-%APPVEYOR_REPO_TAG_NAME%.exe
- cd ..
- dir

artifacts:
  - path: 'trillium-tester-windows-*.exe'

deploy:
  provider: GitHub
  auth_token:
    secure: 4qw1Dg0GFj2kJVi7uCOm6AYeNUGHpvCejJVC0HJp+uvQVofMJNh9U6Cu29O4VuN9
  artifact: /trillium-tester-windows-.*\.exe/
  description: Automatic windows build
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
