before_build:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe
- set PATH=C:\msys64\usr\bin;%PATH%
- pacman -Sy mingw64/mingw-w64-x86_64-libusb pkg-config --noconfirm

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
    TMP: "c:\\tmp"

build_script:
- stack setup
- stack build --extra-include-dirs=C:\msys64\mingw64\include\libusb-1.0 --extra-lib-dirs=C:\msys64\mingw64\bin
- sh: cp .stack-work/*/bin/trillium.exe .
- sh: >
    mv trillium.exe trillium-windows-x86_64-$(grep -Po 'version: *\K[0-9.]+' trillium.cabal).exe

deploy:
  release: trillium-tester-$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: 4qw1Dg0GFj2kJVi7uCOm6AYeNUGHpvCejJVC0HJp+uvQVofMJNh9U6Cu29O4VuN9
  artifact: /trillium.*.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
