resolver: lts-11.22
packages:
  - .
extra-deps:
  - usb-1.3.0.6
  - bindings-libusb-1.4.5.0
  - normaldistribution-1.1.0.3
  - git: https://github.com/UBCOrbit/hstlink.git
    commit: 474d498f6f6547a4b66c58c0a45683de2e367da1
nix:
  packages: [ libusb pkgconfig ]
